basePath: /api/v1
definitions:
  github_com_lshigami_Ringtails_internal_dto.AnswerResponseDTO:
    properties:
      ai_feedback:
        type: string
      ai_score:
        type: number
      id:
        type: integer
      question:
        allOf:
        - $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.QuestionResponseDTO'
        description: Contains full question details
      question_id:
        type: integer
      user_answer:
        type: string
    type: object
  github_com_lshigami_Ringtails_internal_dto.ErrorResponse:
    properties:
      details:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  github_com_lshigami_Ringtails_internal_dto.QuestionCreateDTO:
    properties:
      given_word1:
        type: string
      given_word2:
        type: string
      image_url:
        type: string
      max_score:
        type: number
      order_in_test:
        maximum: 8
        minimum: 1
        type: integer
      prompt:
        type: string
      title:
        type: string
      type:
        enum:
        - sentence_picture
        - email_response
        - opinion_essay
        type: string
    required:
    - max_score
    - order_in_test
    - prompt
    - title
    - type
    type: object
  github_com_lshigami_Ringtails_internal_dto.QuestionResponseDTO:
    properties:
      given_word1:
        type: string
      given_word2:
        type: string
      id:
        type: integer
      image_url:
        type: string
      max_score:
        type: number
      order_in_test:
        type: integer
      prompt:
        type: string
      test_id:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestAttemptDetailDTO:
    properties:
      answers:
        description: List of answers with their details
        items:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.AnswerResponseDTO'
        type: array
      id:
        type: integer
      scaled_score:
        description: Điểm đã quy đổi
        type: number
      status:
        type: string
      submitted_at:
        type: string
      test_id:
        type: integer
      test_title:
        type: string
      total_raw_score:
        description: Điểm thô
        type: number
      user_id:
        type: integer
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestAttemptSubmitDTO:
    properties:
      answers:
        items:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.UserAnswerDTO'
        type: array
      user_id:
        description: Temporary, for non-auth user identification
        type: integer
    required:
    - answers
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestAttemptSummaryDTO:
    properties:
      id:
        type: integer
      scaled_score:
        description: Điểm đã quy đổi
        type: number
      status:
        type: string
      submitted_at:
        type: string
      test_id:
        type: integer
      total_raw_score:
        description: Điểm thô
        type: number
      user_id:
        type: integer
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestCreateDTO:
    properties:
      description:
        type: string
      questions:
        items:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.QuestionCreateDTO'
        maxItems: 8
        minItems: 8
        type: array
      title:
        type: string
    required:
    - questions
    - title
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestResponseDTO:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      questions:
        items:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.QuestionResponseDTO'
        type: array
      title:
        type: string
    type: object
  github_com_lshigami_Ringtails_internal_dto.TestSummaryDTO:
    properties:
      created_at:
        type: string
      description:
        type: string
      has_attempted_by_user:
        type: boolean
      id:
        type: integer
      last_attempt_raw_score:
        description: Đổi tên TotalScore thành RawScore
        type: number
      last_attempt_scaled_score:
        description: Thêm điểm quy đổi
        type: number
      last_attempt_status:
        type: string
      question_count:
        type: integer
      title:
        type: string
    type: object
  github_com_lshigami_Ringtails_internal_dto.UserAnswerDTO:
    properties:
      question_id:
        type: integer
      user_answer:
        type: string
    required:
    - question_id
    - user_answer
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: API for TOEIC Writing practice with structured tests and AI feedback.
    Designed for full test submissions and history.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TOEIC Writing Practice API (Revised V1)
  version: "2.0"
paths:
  /admin/tests:
    post:
      consumes:
      - application/json
      description: Admin creates a new test with exactly 8 questions. All questions
        must be provided.
      parameters:
      - description: Test creation data including all questions (must be 8 questions)
        in: body
        name: test_data
        required: true
        schema:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestCreateDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Test created successfully
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestResponseDTO'
        "400":
          description: Invalid input data (e.g., not 8 questions, missing fields)
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (Admin) Create a new complete test
      tags:
      - Admin - Tests
  /test-attempts/{attempt_id}:
    get:
      description: Retrieve full details of a single test attempt, including all answers,
        scores, and feedback.
      parameters:
      - description: Test Attempt ID
        in: path
        name: attempt_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestAttemptDetailDTO'
        "400":
          description: Invalid Test Attempt ID format
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "404":
          description: Test Attempt not found
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (User) Get details of a specific test attempt
      tags:
      - User - Tests & Attempts
  /tests:
    get:
      description: Get a list of tests. If 'user_id' query param is provided, includes
        attempt status for that user.
      parameters:
      - description: Optional User ID to check attempt status against
        in: query
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestSummaryDTO'
            type: array
        "400":
          description: Invalid User ID format
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (User) List all available tests
      tags:
      - User - Tests & Attempts
  /tests/{test_id}:
    get:
      description: Get full details of a test, including all its questions, for a
        user to start an attempt.
      parameters:
      - description: Test ID
        in: path
        name: test_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestResponseDTO'
        "400":
          description: Invalid Test ID format
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "404":
          description: Test not found
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (User) Get details of a specific test
      tags:
      - User - Tests & Attempts
  /tests/{test_id}/attempts:
    post:
      consumes:
      - application/json
      description: User submits answers for questions in a specific test. AI scoring
        happens in the background.
      parameters:
      - description: ID of the Test being attempted
        in: path
        name: test_id
        required: true
        type: integer
      - description: User ID (optional for now) and list of answers
        in: body
        name: submission_data
        required: true
        schema:
          $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestAttemptSubmitDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Attempt submitted and processing started. Details might be
            partial until scoring completes.
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestAttemptDetailDTO'
        "400":
          description: Invalid input (e.g., bad Test ID, invalid answers format)
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "404":
          description: Test not found
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Error processing submission
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (User) Submit answers for an entire test
      tags:
      - User - Tests & Attempts
  /tests/{test_id}/my-attempts:
    get:
      description: Retrieve a list of summary information for all attempts a user
        made on a test.
      parameters:
      - description: Test ID
        in: path
        name: test_id
        required: true
        type: integer
      - description: User ID to filter attempts. (Temporary - will be from auth token)
        in: query
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.TestAttemptSummaryDTO'
            type: array
        "400":
          description: Invalid ID format for Test ID or User ID
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_lshigami_Ringtails_internal_dto.ErrorResponse'
      summary: (User) Get all attempts by a user for a specific test
      tags:
      - User - Tests & Attempts
schemes:
- http
- https
swagger: "2.0"
